version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: python app.py

  frontend:
    build: ./hubspot
    ports:
      - "3000:3000"
    volumes:
      - ./hubspot:/app
      - /app/node_modules
    environment:
      - BACKEND_URL=http://localhost:5000
    command: npm run dev
